'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _10DimensionSapproach
    
    '''<summary>
    '''DrlTimeYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlTimeYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlTimeMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlTimeMonth As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlScenario As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drlsimcom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drlsimcom As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drloem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drloem As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HdfTypeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfTypeReport As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''DrlTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlTop As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlSort As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBegin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtContain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtContain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DrlAssetType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlAssetType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlCRMType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlCRMType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlObligorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlObligorType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlArrearsStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlArrearsStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlExternalCreditRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlExternalCreditRating As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlObligorIndustryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlObligorIndustryGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlExposureCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlExposureCurrency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlCountryOfOrigin As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnOkCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOkCondition As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ReportViewer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer2 As Global.Microsoft.Reporting.WebForms.ReportViewer
End Class
